# This is a basic workflow to help you get started with Actionsasdasdasd
asdasdasda
name: CI11143214321asdasd
asdasdad
# Controls when the workflow will runasdasd
on:431242432144321dsaasdasd
  # Triggers the workflow on push or pul321213123l asdasdasdrequest events but only for the "main" dsadsaranch
  push:4321424dsaddsadsaasdasdasdasd
    branches: [ "main" ]dsad
  pull_request:43124124dasdasdsad
    branches: [ "main" ]321312dsadsadasdsdaddsadadasdasd
  # Allows you to run this workflow manually froasdam the Actions tabdsadsaasdasd
  workflow_dispatch:dsad

# A workflow run is made up of one or more jobs that can run sequentially or in paral3213213lel
jobs:
  # This workflow contains a single job called "build"
  build:3213123
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
